root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build"
  bin = "tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "magenta"
  runner = "green"

[misc]
  clean_on_exit = true

